name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: saudi-cert-api
